### ISSUE TITLE
Segfault on launch

### ISSUE THREAD

**Issue by mrbojangles3** [alexandervdm/gummi#181]
**Describe the bug**
Gummi Segfaults on Fedora 36

**To Reproduce**
launch gummi via cli
observe segfault message

**System:**
 - OS: Fedora 36
 - Gummi version 
Installed Packages
Name         : gummi
Version      : 0.6.6
Release      : 15.fc36
Architecture : x86_64
Size         : 1.2 M
Source       : gummi-0.6.6-15.fc36.src.rpm
Repository   : @System
From repo    : fedora
Summary      : A simple LaTeX editor
URL          : https://github.com/alexandervdm/gummi
License      : MIT

**Other**
If useful, please include a screenshot or run gummi with the '--debug' flag for extra information
```
$ gummi --debug
Gtk-Message: 11:55:55.186: Failed to load module "pk-gtk-module"
[Info] Gummi version: 0.6.6
[Info] configuration file: /home/lblyth/.config/gummi/gummi.cfg
[Info] Texlive 2021 was found installed..
[Info] Typesetter detected: pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2021)
[Info] Typesetter detected: XeTeX 3.141592653-2.6-0.999993 (TeX Live 2021)
[Info] Segmentation fault (core dumped)
```
gdb back trace
```
Thread 1 "gummi" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
Downloading 0.00 MB source file /usr/src/debug/glibc-2.35-20.fc36.x86_64/string/../sysdeps/x86_64/multiarch/strlen-avx2.S
74		VPCMPEQ	(%rdi), %ymm0, %ymm1
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
#1  0x00007ffff70719f8 in __vfprintf_internal
    (s=s@entry=0x7fffffffb840, format=format@entry=0x5555555920d0 "Typesetter detected: Latexmk %s\n", ap=ap@entry=0x7fffffffb9c0, mode_flags=mode_flags@entry=2) at vfprintf-internal.c:1517
#2  0x00007ffff708202c in __vsnprintf_internal
    (string=string@entry=0x7fffffffb9e0 "Typesetter detected: Latexmk \177", maxlen=<optimized out>, 
    maxlen@entry=8192, format=format@entry=0x5555555920d0 "Typesetter detected: Latexmk %s\n", args=args@entry=0x7fffffffb9c0, mode_flags=mode_flags@entry=2)
    at vsnprintf.c:114
#3  0x00007ffff711f648 in ___vsnprintf_chk
    (s=s@entry=0x7fffffffb9e0 "Typesetter detected: Latexmk \177", maxlen=maxlen@entry=8192, flag=flag@entry=1, slen=slen@entry=8192, format=format@entry=0x5555555920d0 "Typesetter detected: Latexmk %s\n", ap=ap@entry=0x7fffffffb9c0)
    at vsnprintf_chk.c:34
#4  0x0000555555587f9e in vsnprintf
    (__ap=0x7fffffffb9c0, __fmt=0x5555555920d0 "Typesetter detected: Latexmk %s\n", __n=8192, __s=0x7fffffffb9e0 "Typesetter detected: Latexmk \177")
    at /usr/include/bits/stdio2.h:85
#5  slog
    (level=level@entry=0, fmt=fmt@entry=0x5555555920d0 "Typesetter detected: Latexmk %s\n") at /usr/src/debug/gummi-0.6.6-15.fc36.x86_64/src/utils.c:113
--Type <RET> for more, q to quit, c to continue without paging--c
#6  0x000055555558cef3 in latexmk_init () at compile/latexmk.c:43
#7  latexmk_init () at compile/latexmk.c:39
#8  latex_init () at /usr/src/debug/gummi-0.6.6-15.fc36.x86_64/src/latex.c:62
#9  0x000055555556a0ef in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/gummi-0.6.6-15.fc36.x86_64/src/main.c:128
```

**Comment by mrbojangles3** [comment]
This does not happen on Fedora 37

**Comment by alexandervdm** [comment]
Fedora is still repackaging a six year old release. I send the maintainers a quick email just now to request bumping the package.

**Comment by alexandervdm** [comment]
Never got a reply. I consider Gummi on Fedora as unmaintained. If you want to continue using Gummi I recommend the Flatpak or compiling from source.

**Comment by mrbojangles3** [comment]
Thank you for following up on this. I enjoy using Gummi, so I will do as you have instructed.

**Comment by alexandervdm** [comment]
You are most welcome!
