### ISSUE TITLE
Segmentation fault under Arch Linux

### ISSUE THREAD

**Issue by airon90** [alexandervdm/gummi#81]
Hi, I cannot open any LaTeX file with gummi because it keeps on crashing.

I'm using latest version of Arch Linux and official Arch Linux package of gummi.

I used gdb to debug and here is the output:

```
(gdb) bt full
#0  0x00007ffff6271899 in g_type_check_instance ()
    at /usr/lib/libgobject-2.0.so.0
#1  0x00007ffff6264740 in g_signal_handler_is_connected ()
    at /usr/lib/libgobject-2.0.so.0
#2  0x0000000000414b01 in editor_destroy ()
#3  0x00000000004191b1 in tabmanagergui_replace_page ()
#4  0x000000000043494e in tabmanager_create_tab ()
#5  0x000000000041a4c1 in gui_open_file ()
#6  0x0000000000417668 in on_menu_open_activate ()
#7  0x00007ffff6249c5d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff625db50 in  () at /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff6266806 in g_signal_emit_valist ()
    at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff626771c in g_signal_emit_by_name ()
    at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff6249c5d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff625db50 in  () at /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff6266806 in g_signal_emit_valist ()
    at /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff6267240 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff730a895 in  () at /usr/lib/libgtk-x11-2.0.so.0
#16 0x00007ffff6249c5d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff625dc28 in  () at /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff6266806 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#19 0x00007ffff6267240 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#20 0x00007ffff73097ba in  () at /usr/lib/libgtk-x11-2.0.so.0
#21 0x00007ffff73b27cc in  () at /usr/lib/libgtk-x11-2.0.so.0
#22 0x00007ffff6249c5d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#23 0x00007ffff625d5aa in  () at /usr/lib/libgobject-2.0.so.0
#24 0x00007ffff6266191 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#25 0x00007ffff6267240 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#26 0x00007ffff74cd235 in  () at /usr/lib/libgtk-x11-2.0.so.0
#27 0x00007ffff73b0a0e in gtk_propagate_event () at /usr/lib/libgtk-x11-2.0.so.0
#28 0x00007ffff73b0e43 in gtk_main_do_event () at /usr/lib/libgtk-x11-2.0.so.0
#29 0x00007ffff7029d5e in  () at /usr/lib/libgdk-x11-2.0.so.0
#30 0x00007ffff7b0de38 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#31 0x00007ffff7b0e081 in  () at /usr/lib/libglib-2.0.so.0
#32 0x00007ffff7b0e3b2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#33 0x00007ffff73afdf3 in gtk_main () at /usr/lib/libgtk-x11-2.0.so.0
#34 0x000000000041a155 in gui_main ()
#35 0x000000000041382c in main ()
```

**Comment by airon90** [comment]
Fixed.
